#include "print.h"
void main(){
put_char('k');	
put_char('e');	
put_char('r');	
put_char('n');	
put_char('e');	
put_char('l');	
put_char('i');	
put_char('i');	
put_char('i');	
put_char('i');	
put_char('i');	
put_char('i');	
put_char('i');	
put_char('i');	
put_char('i');	
put_char('i');	
put_char('i');	
put_char('i');	
put_char('i');	
put_char('i');	
put_char('i');	
put_char('i');	
put_char('i');	
put_char('i');	
put_char('i');	
put_char('i');	
put_char('i');	
put_char('i');	
put_char('i');	
put_char('i');	
put_char('i');	
put_char('i');	
put_char('i');	
put_char('i');	
put_char('i');	
put_char('i');	
put_char('i');	
while(1);
}

